name: RSpec Tests

on:
  push:
    branches:
      - main
      - work
      - add_tests
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test_database
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3'

      - name: Install dependencies
        run: bundle install

      - name: Wait for PostgreSQL
        run: |
          sleep 10
          until pg_isready -h 127.0.0.1 -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done

      - name: Check PostgreSQL state
        run: docker ps

      - name: Set up database
        run: |
          bin/rails db:create RAILS_ENV=test || echo "Failed to create database"
          bin/rails db:schema:load RAILS_ENV=test || echo "Failed to load schema"

      - name: Run tests
        run: bundle exec rspec
